# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# This is the processing pipeline from the multiple views semantic/RGB-D images to 3D point clouds.

envs:
  proc_alias: str3dr001mvp        # resolution 0.01m with perspective and panorama multiple views
  io_paths:
    # Raw data folder
    raw_data_dir: $in_data_root$
    out_data_dir: $out_data_root$
    # Point cloud data folder
    point_cloud_dir: $out_data_root$/points
    semantic_dir: $out_data_root$/semantic_mask
    anno_dir: $out_data_root$/anno_mask
    instance_dir: $out_data_root$/instance_mask
    # Analysis results folder and files
    analysis_dir: $out_data_root$/analysis
    num_points_dist_path: $analysis_dir$/points.xlsx
    room_sizes_dist_path: $analysis_dir$/sizes.xlsx
    category_dist_path: $analysis_dir$/categories.xlsx
    nearest_neighbor_dist_path: $analysis_dir$/nearest.xlsx
    top_view_dir: $analysis_dir$/top_view
    3d_vis_dir: $analysis_dir$/3d_vis

streaming_lines:
-
  assemble_class: 'Structured3DDataGen'
  process_pipelines:
    -
      assemble_function: format_dataset
      attrs: {room_types: [all]}
      in_paths: [raw_data_dir]
      out_paths: [point_cloud_dir, semantic_dir, instance_dir, anno_dir]
-
  assemble_class: 'SampleWiseProcessing'
  process_pipelines:
    -
      assemble_function: PLY3DVisualization
      name: 3d_rgb
      attrs: {w_boxes: 1, color_scheme: nyu40}
      stride: 50
      in_paths: [point_cloud_dir]
      out_paths: [3d_vis_dir]
    -
      assemble_function: PLY3DVisualization
      name: 3d_label
      attrs: {w_labels: 1, color_scheme: nyu40}
      stride: 50
      in_paths: [point_cloud_dir, semantic_dir]
      out_paths: [3d_vis_dir]
-
  assemble_class: 'MMDet3DDownStreaming'
  process_pipelines:
    -
      assemble_function: detection
      in_paths: [out_data_root]
      out_paths: [out_data_root]
# -
#   assemble_class: 'PointCloudStatistics'
#   process_pipelines:
    # -
    #   assemble_function: CategoryDistribution
    #   name: categories
    #   attrs: {num_categories: 41}
    #   in_paths: [point_cloud_dir]
    #   out_paths: [category_dist_path]
    # -
    #   assemble_function: NumPointsDistribution
    #   name: num_points
    #   attrs: {stride: 10000}
    #   in_paths: [point_cloud_dir]
    #   out_paths: [num_points_dist_path]
    # -
    #   assemble_function: NearestNeighborDistribution  # Time-consuming due to KD-Tree build
    #   stride: 5
    #   name: nearest_neighbor
    #   attrs: {stride: 0.001, max: 0.2}
    #   in_paths: [point_cloud_dir]
    #   out_paths: [nearest_neighbor_dist_path]

    # -
    #   assemble_function: TopViewVisualization
    #   name: top_view_rgb
    #   stride: 50
    #   attrs: {stride: 100, resolution: 0.01, key_pos: points, key_vis: colors, top_axis: y}
    #   in_paths: [point_cloud_dir]
    #   out_paths: [top_view_dir]
    # -
    #   assemble_function: TopViewVisualization
    #   name: top_view_label
    #   stride: 50
    #   attrs: {resolution: 0.01, key: labels, top_axis: y, color_scheme: nyu40}
    #   in_paths: [point_cloud_dir]
    #   out_paths: [top_view_dir]
# -
#   assemble_class: 'PointCloudDownStreaming'
#   process_pipelines:
#     -
#       assemble_function: segmentation
#       attrs: {keys: 'points', 'colors', 'labels'}
#       in_paths: [point_cloud_dir]
#       out_paths: [train_sets_dir]
