# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# This is the processing pipeline from the multiple views semantic/RGB-D images to 3D point clouds.

envs:
  proc_alias: str3dr001mvp        # resolution 0.01m with perspective and panorama multiple views
  io_paths:
    # Raw data folder
    raw_data_dir: $in_data_root$/raw
    # Point cloud data folder
    point_cloud_dir: $out_data_root$/point_cloud
    # Analysis results folder and files
    analysis_dir: $out_data_root$/analysis
    num_points_dist_path: $analysis_dir$/points.xlsx
    room_sizes_dist_path: $analysis_dir$/sizes.xlsx
    category_dist_path: $analysis_dir$/categories.xlsx
    nearest_neighbor_dist_path: $analysis_dir$/nearest.xlsx
    top_view_dir: $analysis_dir$/top_view 
    # Training dataset folder
    train_sets_dir: $out_data_root$/str3ds25v0

streaming_lines:
# -
#   assemble_class: 'Structured3DDataGen'
#   process_pipelines:
#     -
#       assemble_function: view2pointcloud
#       attrs: {room_types: [all]}
#       in_paths: [raw_data_dir]
#       out_paths: [point_cloud_dir]
-
  assemble_class: 'PointCloudStatistics'
  process_pipelines:
    -
      assemble_function: CategoryDistribution
      name: categories
      attrs: {num_categories: 41}
      in_paths: [point_cloud_dir]
      out_paths: [category_dist_path]
    -
      assemble_function: NumPointsDistribution
      name: num_points
      attrs: {stride: 10000}
      in_paths: [point_cloud_dir]
      out_paths: [num_points_dist_path]
    -
      assemble_function: NearestNeighborDistribution  # Time-consuming due to KD-Tree build
      stride: 5
      name: nearest_neighbor
      attrs: {stride: 0.001, max: 0.2}
      in_paths: [point_cloud_dir]
      out_paths: [nearest_neighbor_dist_path]
    # -
    #   assemble_function: TopViewVisualization
    #   name: top_view_rgb
    #   stride: 50
    #   attrs: {stride: 100, resolution: 0.01, key: colors, top_axis: y_top}
    #   in_paths: [point_cloud_dir]
    #   out_paths: [top_view_dir]
    # -
    #   assemble_function: TopViewVisualization
    #   name: top_view_label
    #   stride: 50
    #   attrs: {resolution: 0.01, key: labels, top_axis: y_top, color_scheme: nyu40}
    #   in_paths: [point_cloud_dir]
    #   out_paths: [top_view_dir]
# -
#   assemble_class: 'PointCloudDownStreaming'
#   process_pipelines:
#     -
#       assemble_function: segmentation
#       attrs: {keys: 'points', 'colors', 'labels'}
#       in_paths: [point_cloud_dir]
#       out_paths: [train_sets_dir]
